### ISSUE TITLE
BRAT

### ISSUE THREAD

**Issue by abdcef** [hanbyul-kim/Bike-to-Obsidian#1]
Hi. Thanks for this. Can you make the plugin compatible with BRAT? It would simplify the installation process.

**Comment by hanbyul-kim** [comment]
Hi, I’ve tried BRAT recently. I’ll check it out this weekend.

**Comment by abdcef** [comment]
great, thanks!

I'm curious how you use both Bike and Obsidian. is Bike for capture and then you copy to Obsidian every say end of day? Do you retain information in both?

**Comment by hanbyul-kim** [comment]
Nowadays, I separate the purpose of notes from Bike and Obsidian. I don't feel necessity to export notes from here to there.

**Comment by abdcef** [comment]
Got it. How do you access your Bike files on mobile (ios)?

**Comment by hanbyul-kim** [comment]
> Got it. How do you access your Bike files on mobile (ios)?

I use Taio to monitor bike files. Honestly, I don't do it very commonly.

**Comment by hanbyul-kim** [comment]
I support BRAT installation by releasing my plugin files. Tested and looks working well. Please check it out.

**Comment by hanbyul-kim** [comment]
Although I closed this issue, you can discuss anything with me. Feel free to leave messages.
